### ISSUE TITLE
Local IP Address

### ISSUE THREAD

**Issue by nelsonic** [jackcarlisle/code-notes#3]
@jackcarlisle when checking the IP address of your localhost, if you want to have to dig through _fewer_ lines in the output of `ifconfig` you can try: 

``` sh
ifconfig | grep inet
```

Which will restrict the output to:
![ifconfig-grep-inet](https://cloud.githubusercontent.com/assets/194400/16191876/42cba040-36de-11e6-9710-508b78636abc.png)

see: https://github.com/jackcarlisle/code-notes/tree/203042187a4f19783784ebca8d5d4365cc3cbff3#how-to-access-localhost-on-a-mobile-device-when-using-a-webpack-dev-server

**Comment by jackcarlisle** [comment]
awesome thanks @nelsonic !
